#!/usr/bin/env python3
"""Generate docs/index.md — Jekyll Pages landing for the AI4Chem feed.

Contents:
  - Total corpus stats (paper count, months, last update)
  - Tag cloud sorted by 30-day frequency (size visually = recency × volume)
  - Top recent papers across all topics, with their tags

URL: <user>.github.io/<repo>/  →  this index.
"""
import argparse
import html
import logging
import sys
from collections import Counter
from datetime import date, datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import data_io
import tag_matcher

LOG = logging.getLogger("render_index")

DEFAULT_OUT = data_io.ROOT / "docs" / "index.md"
DEFAULT_TAG_INDEX = data_io.ROOT / "docs" / "_data" / "tag_index.yml"
WINDOW_DAYS = 30
RECENT_PAPERS = 30


def _within(updated_str, days):
    cutoff = date.today() - timedelta(days=days)
    return datetime.strptime(updated_str, "%Y-%m-%d").date() >= cutoff


def _tag_cloud_entries(papers_by_tag, canonical):
    """Return sorted list of (tag, recent_freq, total_freq, group)."""
    rows = []
    for tag in canonical:
        all_papers = papers_by_tag.get(tag, [])
        recent = [p for p in all_papers if _within(p[1]["updated"], WINDOW_DAYS)]
        group = canonical[tag].get("group", "other") if isinstance(canonical[tag], dict) else "other"
        rows.append((tag, len(recent), len(all_papers), group))
    rows.sort(key=lambda r: -r[1])
    return rows


def _corpus_stats(by_month):
    total = sum(len(m) for m in by_month.values())
    months = len([m for m in by_month if by_month[m]])
    return total, months


def _recent_papers(by_month, limit):
    flat = []
    for month, papers in by_month.items():
        for pid, rec in papers.items():
            flat.append((pid, rec))
    flat.sort(key=lambda x: x[1]["updated"], reverse=True)
    return flat[:limit]


def _write_tag_index(rows, out_path):
    """Write _data/tag_index.yml — single source for sidebar.

    Sorted alphabetically; only tags with >0 recent papers OR present in canonical
    are emitted (we keep 0-count tags so the sidebar reflects the full vocabulary).
    """
    rows_sorted = sorted(rows, key=lambda r: (-r[1], r[0]))
    lines = ["# Generated by tools/render_index.py — do not edit by hand."]
    for tag, recent_n, total_n, group in rows_sorted:
        lines.append(f"- name: {tag}")
        lines.append(f"  count: {recent_n}")
        lines.append(f"  total: {total_n}")
        lines.append(f"  group: {group}")
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    LOG.info(f"wrote {out_path}")


def run(canonical_path, out_path, tag_index_path=None):
    canonical = tag_matcher.load_canonical_tags(canonical_path)
    by_month, _ = data_io.load_all_months()
    total_papers, total_months = _corpus_stats(by_month)

    # Bucket by tag
    papers_by_tag = {}
    for month, papers in by_month.items():
        for pid, rec in papers.items():
            for t in rec.get("tags", []):
                papers_by_tag.setdefault(t, []).append((pid, rec))

    rows = _tag_cloud_entries(papers_by_tag, canonical)
    today = date.today()

    if tag_index_path is None:
        tag_index_path = DEFAULT_TAG_INDEX
    _write_tag_index(rows, tag_index_path)

    lines = []
    lines.append("---")
    lines.append("layout: page")
    lines.append('title: "AI4Chem arxiv-radar"')
    lines.append("---")
    lines.append("")
    lines.append("# AI4Chem arxiv-radar")
    lines.append("")
    lines.append(f"_Updated {today.isoformat()}._")
    lines.append("")
    lines.append(f"**{total_papers}** chemistry-relevant papers across "
                 f"**{total_months}** months. "
                 f"Pre-curated tag pages with 5 time windows (7d / 30d / 90d / 360d / all). "
                 f"Browse the **tag list →** in the right sidebar.")
    lines.append("")

    # Recent papers section — same HTML table style as tag pages: class="papers",
    # title wrapped as popup-link, tags as sub-line under title.
    recent = _recent_papers(by_month, RECENT_PAPERS)
    if recent:
        lines.append(f"## Recent papers (top {RECENT_PAPERS})")
        lines.append("")
        lines.append('<table class="papers">')
        lines.append("<thead><tr><th>Date</th><th>Title</th>"
                     "<th>Authors</th><th>arXiv</th></tr></thead>")
        lines.append("<tbody>")
        for pid, rec in recent:
            title = html.escape(rec["title"].replace("\n", " "))
            authors = html.escape(rec["first_author"]) + (
                " et al." if len(rec["authors"]) > 1 else "")
            title_link = (
                f'<a class="abstract-popup paper-title-link" '
                f'href="abstracts/{html.escape(pid)}.html">{title}</a>')
            tags = rec.get("tags", [])
            if tags:
                tag_links = " · ".join(
                    f'<a href="tag/{html.escape(t)}-{WINDOW_DAYS}d.html">'
                    f'{html.escape(t)}</a>'
                    for t in tags)
                title_cell = (
                    f'<div class="paper-title">{title_link}</div>'
                    f'<div class="paper-tags">{tag_links}</div>')
            else:
                title_cell = f'<div class="paper-title">{title_link}</div>'
            lines.append('<tr class="paper">')
            lines.append(f'<td>{rec["updated"]}</td>')
            lines.append(f'<td>{title_cell}</td>')
            lines.append(f'<td>{authors}</td>')
            lines.append(
                f'<td><a href="http://arxiv.org/abs/{pid}">{pid}</a></td>')
            lines.append("</tr>")
        lines.append("</tbody></table>")
        lines.append("")

    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    LOG.info(f"wrote {out_path}")
    return {
        "total_papers": total_papers,
        "total_months": total_months,
        "total_tags": len(canonical),
        "tags_with_papers": sum(1 for t, r, total, g in rows if total > 0),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--canonical", default=None)
    parser.add_argument("--out", default=None)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO,
                        format="[%(asctime)s %(levelname)s] %(message)s",
                        datefmt="%H:%M:%S")
    canonical_path = Path(args.canonical) if args.canonical else (
        data_io.ROOT / "tags" / "canonical.yaml")
    out = Path(args.out) if args.out else DEFAULT_OUT
    run(canonical_path, out)


if __name__ == "__main__":
    main()
